### ISSUE TITLE
Use adb for interacting with emulator

### ISSUE THREAD

**Issue by GavriloviciEduard** [Pbatch/ClashRoyaleBuildABot#4]
What do you think about using the android debug bridge for interacting with the emulator. I think this solution would be more reliable instead of using the Windows API(e.g. you don't have to call set foreground window before taking a screenshot of the current state). Also opening, closing, restarting the game would be easy to implement. I can make a pull request if you think you'd find it useful.

**Comment by Pbatch** [comment]
This is a very good idea because I don't think there is a cross-platform tool for interacting with windows yet. I'm happy to work with you if you think you can put something useful together :) 

I'm away this weekend but will write some contribution guidelines on Monday, as well as list some priority features. Of course anyone is welcome to suggest ideas that can help to drive the project forward! 

At one point I will add the YOLOv5 training notebook as there is quite a lot of scope to make the models better, mostly involving labelling more classes. 

It would be nice to have some more beginner bots to help players learn about various ML topics I.e. Imitation learning, Q-learning etc.

From a more software perspective, various other functions for interacting with the app would be useful too. (Opening chests, levelling up, etc.). It would also be nice to record more game history, and collate various stats of what is going on.

Just a few things off the top of my head. There are lots of ways to improve the project so anyone who contributes should be able to find something they enjoy.

**Comment by Pbatch** [comment]
#18 Adds ADB! All platforms work now :)
