### ISSUE TITLE
[help wanted] How to get enemy position

### ISSUE THREAD

**Issue by Jimase** [Pbatch/ClashRoyaleBuildABot#68]
In the demo.gif  you provide 
![demo](https://raw.githubusercontent.com/wiki/Pbatch/ClashRoyaleBuildABot/images/demo.gif)
It seems that I can get the tag like "ally_knight" or "enemy_knight" , but I only see 
![784](https://user-images.githubusercontent.com/90017313/226554621-cd12a173-89b1-4d9e-b09e-bbc25701257e.jpg)
And why the blood of the princess tower is "-1"

**Comment by Pbatch** [comment]
Hello.

In a recent patch the side (ally/enemy) of the unit is predicted separately. You can access it in the metadata of the object but it's not plotted in the debug diagrams. I can change this if you want?

The blood of the princess tower is "-1" because the bounding box for the hp is in the wrong place. I think this might be because they're using a skin, but it may also be because of the map. I have seen this issue before so will add it as a TODO. If you want a temporary fix, you can try changing `ENEMY_PRINCESS_HP_Y = 93` in `clashroyalebuildabot/data/constants.py`. Thanks for reporting the issue :)

**Comment by Jimase** [comment]
Hello, I tried modifying ENEMY_PRINCESS_HPi_Y = 93 in the clashroyalebuildabot/data/constants.py file, and it really worked.

I am currently trying to collect some X-Bow videos. If possible, could you please give me the version that can detect allies/enemies? It would be of great help to me. This project is so amazing that it might take me quite a long time to learn.

I also want to try to create an X-Bow AI by imitating the 2.6 Hog Rider deck.
